# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.voice_parameters import VoiceParameters

class TestVoiceParameters(unittest.TestCase):
    """VoiceParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceParameters:
        """Test VoiceParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceParameters`
        """
        model = VoiceParameters()
        if include_optional:
            return VoiceParameters(
                description = '',
                name = 'jUR,rZ#UM/?R,Fp^l6$ARjQJk C>i H\'qT\\{<?\'es#)#iK.YM{Rag2/!KB!k@5oXh.:Ts\";mGL,i&z5[P@M\"lzfB+Y,Twzfu~N^z\"mfqecVU{S0',
                remove_background_noise = True
            )
        else:
            return VoiceParameters(
                name = 'jUR,rZ#UM/?R,Fp^l6$ARjQJk C>i H\'qT\\{<?\'es#)#iK.YM{Rag2/!KB!k@5oXh.:Ts\";mGL,i&z5[P@M\"lzfB+Y,Twzfu~N^z\"mfqecVU{S0',
        )
        """

    def testVoiceParameters(self):
        """Test VoiceParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
