# coding: utf-8

"""
    mm-gateway

    Unified image, video, and music gateway with separate REST APIs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.music_request import MusicRequest

class TestMusicRequest(unittest.TestCase):
    """MusicRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MusicRequest:
        """Test MusicRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MusicRequest`
        """
        model = MusicRequest()
        if include_optional:
            return MusicRequest(
                input = [
                    null
                    ],
                metadata = { },
                model = '',
                parameters = mmgateway.models.music_parameters.MusicParameters(
                    bitrate_kbps = 8.0, 
                    bpm = 1.0, 
                    duration_seconds = 0.0, 
                    enhance_lyrics = True, 
                    file_format = '', 
                    guidance_scale = 0.0, 
                    inference_steps = 1.0, 
                    instrumental = True, 
                    key = '', 
                    negative_prompt = '', 
                    novelty = 0.0, 
                    output_count = 1.0, 
                    provenance = True, 
                    reference_audio_strength = 0.0, 
                    respect_section_durations = True, 
                    sample_rate_hz = 8000.0, 
                    scale = '', 
                    seed = 56, 
                    style = '', 
                    style_strength = 0.0, 
                    time_signature = '', 
                    title = '', 
                    vocal_gender = '', 
                    vocal_language = '', 
                    voice = '', ),
                routing = mmgateway.models.routing_directive.RoutingDirective(
                    profile = '0', )
            )
        else:
            return MusicRequest(
                input = [
                    null
                    ],
        )
        """

    def testMusicRequest(self):
        """Test MusicRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
