# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.management_config_response import ManagementConfigResponse

class TestManagementConfigResponse(unittest.TestCase):
    """ManagementConfigResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagementConfigResponse:
        """Test ManagementConfigResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagementConfigResponse`
        """
        model = ManagementConfigResponse()
        if include_optional:
            return ManagementConfigResponse(
                config = mmgateway.models.management_config.ManagementConfig(
                    backends = [
                        mmgateway.models.managed_backend.ManagedBackend(
                            api_key = '', 
                            base_url = '', 
                            credentials = [
                                mmgateway.models.backend_credential.BackendCredential(
                                    api_key = '', 
                                    base_url = '', 
                                    extra = { }, 
                                    id = 'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM.:fvlxVU:5mAsDwtJsoLm0U2QzcAPbMGoFtYYnOi3Uynm7-iBPXDeXK7FerdNFR', )
                                ], 
                            enabled = True, 
                            extra = { }, 
                            name = 'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM.:fvlxVU:5mAsDwtJsoLm0U2QzcAPbMGoFtYYnOi3Uynm7-iBPXDeXK7FerdNFR', 
                            tags = [
                                ''
                                ], 
                            type = '0', )
                        ], 
                    budget_allow_unpriced = True, 
                    catalog_models = { }, 
                    keys = [
                        mmgateway.models.managed_key.ManagedKey(
                            allow_backends = [
                                ''
                                ], 
                            allow_tags = [
                                ''
                                ], 
                            budget = null, 
                            default_audio_backend = '', 
                            default_audio_tag = '', 
                            default_image_backend = '', 
                            default_image_tag = '', 
                            default_music_backend = '', 
                            default_music_tag = '', 
                            default_video_backend = '', 
                            default_video_tag = '', 
                            deny_tags = [
                                ''
                                ], 
                            enabled = True, 
                            extra = , 
                            id = 'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM.:fvlxVU:5mAsDwtJsoLm0U2QzcAPbMGoFtYYnOi3Uynm7-iBPXDeXK7FerdNFR', 
                            key = '', )
                        ], 
                    outbound_proxy = '', 
                    proxies = [
                        mmgateway.models.managed_proxy.ManagedProxy(
                            accounts = [
                                mmgateway.models.proxy_account.ProxyAccount(
                                    headers = {
                                        'key' : ''
                                        }, 
                                    id = 'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM.:fvlxVU:5mAsDwtJsoLm0U2QzcAPbMGoFtYYnOi3Uynm7-iBPXDeXK7FerdNFR', )
                                ], 
                            base_url = '', 
                            domain = '', 
                            enabled = True, 
                            headers = {
                                'key' : ''
                                }, 
                            outbound_proxy = '', 
                            tags = [
                                ''
                                ], 
                            timeout = 0.0, )
                        ], 
                    routing_default_optimize = 'balanced', 
                    routing_profiles = {
                        'key' : mmgateway.models.managed_routing_profile.ManagedRoutingProfile(
                            fallback = 'none', 
                            max_cost_usd = 0.0, 
                            optimize = 'balanced', 
                            tags = , )
                        }, ),
                persistent = True,
                revision = ''
            )
        else:
            return ManagementConfigResponse(
                config = mmgateway.models.management_config.ManagementConfig(
                    backends = [
                        mmgateway.models.managed_backend.ManagedBackend(
                            api_key = '', 
                            base_url = '', 
                            credentials = [
                                mmgateway.models.backend_credential.BackendCredential(
                                    api_key = '', 
                                    base_url = '', 
                                    extra = { }, 
                                    id = 'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM.:fvlxVU:5mAsDwtJsoLm0U2QzcAPbMGoFtYYnOi3Uynm7-iBPXDeXK7FerdNFR', )
                                ], 
                            enabled = True, 
                            extra = { }, 
                            name = 'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM.:fvlxVU:5mAsDwtJsoLm0U2QzcAPbMGoFtYYnOi3Uynm7-iBPXDeXK7FerdNFR', 
                            tags = [
                                ''
                                ], 
                            type = '0', )
                        ], 
                    budget_allow_unpriced = True, 
                    catalog_models = { }, 
                    keys = [
                        mmgateway.models.managed_key.ManagedKey(
                            allow_backends = [
                                ''
                                ], 
                            allow_tags = [
                                ''
                                ], 
                            budget = null, 
                            default_audio_backend = '', 
                            default_audio_tag = '', 
                            default_image_backend = '', 
                            default_image_tag = '', 
                            default_music_backend = '', 
                            default_music_tag = '', 
                            default_video_backend = '', 
                            default_video_tag = '', 
                            deny_tags = [
                                ''
                                ], 
                            enabled = True, 
                            extra = , 
                            id = 'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM.:fvlxVU:5mAsDwtJsoLm0U2QzcAPbMGoFtYYnOi3Uynm7-iBPXDeXK7FerdNFR', 
                            key = '', )
                        ], 
                    outbound_proxy = '', 
                    proxies = [
                        mmgateway.models.managed_proxy.ManagedProxy(
                            accounts = [
                                mmgateway.models.proxy_account.ProxyAccount(
                                    headers = {
                                        'key' : ''
                                        }, 
                                    id = 'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM.:fvlxVU:5mAsDwtJsoLm0U2QzcAPbMGoFtYYnOi3Uynm7-iBPXDeXK7FerdNFR', )
                                ], 
                            base_url = '', 
                            domain = '', 
                            enabled = True, 
                            headers = {
                                'key' : ''
                                }, 
                            outbound_proxy = '', 
                            tags = [
                                ''
                                ], 
                            timeout = 0.0, )
                        ], 
                    routing_default_optimize = 'balanced', 
                    routing_profiles = {
                        'key' : mmgateway.models.managed_routing_profile.ManagedRoutingProfile(
                            fallback = 'none', 
                            max_cost_usd = 0.0, 
                            optimize = 'balanced', 
                            tags = , )
                        }, ),
                persistent = True,
                revision = '',
        )
        """

    def testManagementConfigResponse(self):
        """Test ManagementConfigResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
