# coding: utf-8

"""
    mm-gateway

    Unified image, video, and music gateway with separate REST APIs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.api.usage_api import UsageApi


class TestUsageApi(unittest.TestCase):
    """UsageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsageApi()

    def tearDown(self) -> None:
        pass

    def test_get_usage(self) -> None:
        """Test case for get_usage

        Spend and budgets of the authenticated key
        """
        pass


if __name__ == '__main__':
    unittest.main()
