# coding: utf-8

"""
    mm-gateway

    Unified image, video, and music gateway with separate REST APIs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.estimate_candidate import EstimateCandidate

class TestEstimateCandidate(unittest.TestCase):
    """EstimateCandidate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EstimateCandidate:
        """Test EstimateCandidate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EstimateCandidate`
        """
        model = EstimateCandidate()
        if include_optional:
            return EstimateCandidate(
                admissible = True,
                estimated_cost = 1.337,
                lifecycle = 'active',
                model = '',
                reason = ''
            )
        else:
            return EstimateCandidate(
                model = '',
        )
        """

    def testEstimateCandidate(self):
        """Test EstimateCandidate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
