# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.voice_response import VoiceResponse

class TestVoiceResponse(unittest.TestCase):
    """VoiceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceResponse:
        """Test VoiceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceResponse`
        """
        model = VoiceResponse()
        if include_optional:
            return VoiceResponse(
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                error = { },
                id = '',
                kind = 'cloned',
                links = { },
                metadata = { },
                model = '',
                name = '',
                object = 'voice',
                routing = { },
                status = 'pending',
                usage = { },
                verification_required = True
            )
        else:
            return VoiceResponse(
                id = '',
                links = { },
                name = '',
                status = 'pending',
        )
        """

    def testVoiceResponse(self):
        """Test VoiceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
