# coding: utf-8

"""
    mm-gateway

    Unified image, video, and music gateway with separate REST APIs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.usage import Usage

class TestUsage(unittest.TestCase):
    """Usage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Usage:
        """Test Usage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Usage`
        """
        model = Usage()
        if include_optional:
            return Usage(
                cost = 1.337,
                duration_seconds = 1.337,
                input_tokens = 56,
                output_count = 56,
                output_tokens = 56,
                total_tokens = 56
            )
        else:
            return Usage(
        )
        """

    def testUsage(self):
        """Test Usage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
