# coding: utf-8

"""
    mm-gateway

    Unified image, video, and music gateway with separate REST APIs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.video_image_input import VideoImageInput

class TestVideoImageInput(unittest.TestCase):
    """VideoImageInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VideoImageInput:
        """Test VideoImageInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VideoImageInput`
        """
        model = VideoImageInput()
        if include_optional:
            return VideoImageInput(
                role = 'first_frame',
                type = 'image',
                uri = '0'
            )
        else:
            return VideoImageInput(
                type = 'image',
                uri = '0',
        )
        """

    def testVideoImageInput(self):
        """Test VideoImageInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
