# coding: utf-8

"""
    mm-gateway

    Unified image, video, and music gateway with separate REST APIs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.api.images_api import ImagesApi


class TestImagesApi(unittest.TestCase):
    """ImagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImagesApi()

    def tearDown(self) -> None:
        pass

    def test_create_image(self) -> None:
        """Test case for create_image

        Create an image task
        """
        pass

    def test_get_image(self) -> None:
        """Test case for get_image

        Retrieve an image task
        """
        pass


if __name__ == '__main__':
    unittest.main()
