# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.management_status import ManagementStatus

class TestManagementStatus(unittest.TestCase):
    """ManagementStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagementStatus:
        """Test ManagementStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagementStatus`
        """
        model = ManagementStatus()
        if include_optional:
            return ManagementStatus(
                backend_types = [
                    ''
                    ],
                backends = [
                    mmgateway.models.backend_runtime.BackendRuntime(
                        accounts = [
                            ''
                            ], 
                        active = True, 
                        configured = True, 
                        enabled = True, 
                        models = {
                            'key' : [
                                ''
                                ]
                            }, 
                        name = '', 
                        tags = [
                            ''
                            ], 
                        type = '', )
                    ],
                enabled_keys_count = 56,
                keys_count = 56,
                metrics_enabled = True,
                persistent = True,
                proxies = [
                    mmgateway.models.proxy_runtime.ProxyRuntime(
                        accounts = [
                            ''
                            ], 
                        active = True, 
                        domain = '', 
                        enabled = True, )
                    ],
                revision = '',
                status = 'ok',
                tasks_by_status = {
                    'key' : 56
                    },
                uptime_seconds = 1.337,
                version = ''
            )
        else:
            return ManagementStatus(
                backend_types = [
                    ''
                    ],
                backends = [
                    mmgateway.models.backend_runtime.BackendRuntime(
                        accounts = [
                            ''
                            ], 
                        active = True, 
                        configured = True, 
                        enabled = True, 
                        models = {
                            'key' : [
                                ''
                                ]
                            }, 
                        name = '', 
                        tags = [
                            ''
                            ], 
                        type = '', )
                    ],
                enabled_keys_count = 56,
                keys_count = 56,
                metrics_enabled = True,
                persistent = True,
                proxies = [
                    mmgateway.models.proxy_runtime.ProxyRuntime(
                        accounts = [
                            ''
                            ], 
                        active = True, 
                        domain = '', 
                        enabled = True, )
                    ],
                revision = '',
                tasks_by_status = {
                    'key' : 56
                    },
                uptime_seconds = 1.337,
                version = '',
        )
        """

    def testManagementStatus(self):
        """Test ManagementStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
