# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.managed_usage import ManagedUsage

class TestManagedUsage(unittest.TestCase):
    """ManagedUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagedUsage:
        """Test ManagedUsage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagedUsage`
        """
        model = ManagedUsage()
        if include_optional:
            return ManagedUsage(
                enabled = True,
                key_id = '',
                usage = { }
            )
        else:
            return ManagedUsage(
                enabled = True,
                key_id = '',
                usage = { },
        )
        """

    def testManagedUsage(self):
        """Test ManagedUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
