# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.api.audio_api import AudioApi


class TestAudioApi(unittest.TestCase):
    """AudioApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AudioApi()

    def tearDown(self) -> None:
        pass

    def test_create_audio(self) -> None:
        """Test case for create_audio

        Create a speech task
        """
        pass

    def test_create_voice(self) -> None:
        """Test case for create_voice

        Clone a reusable voice
        """
        pass

    def test_estimate_audio(self) -> None:
        """Test case for estimate_audio

        Estimate a speech request
        """
        pass

    def test_estimate_voice(self) -> None:
        """Test case for estimate_voice

        Estimate voice cloning
        """
        pass

    def test_get_audio(self) -> None:
        """Test case for get_audio

        Retrieve a speech task
        """
        pass

    def test_get_voice(self) -> None:
        """Test case for get_voice

        Retrieve a voice or clone task
        """
        pass

    def test_list_voices(self) -> None:
        """Test case for list_voices

        List usable voice presets and owned clones
        """
        pass


if __name__ == '__main__':
    unittest.main()
