# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.managed_backend import ManagedBackend

class TestManagedBackend(unittest.TestCase):
    """ManagedBackend unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagedBackend:
        """Test ManagedBackend
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagedBackend`
        """
        model = ManagedBackend()
        if include_optional:
            return ManagedBackend(
                api_key = '',
                base_url = '',
                credentials = [
                    mmgateway.models.backend_credential.BackendCredential(
                        api_key = '', 
                        base_url = '', 
                        extra = { }, 
                        id = 'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM.:fvlxVU:5mAsDwtJsoLm0U2QzcAPbMGoFtYYnOi3Uynm7-iBPXDeXK7FerdNFR', )
                    ],
                enabled = True,
                extra = { },
                name = 'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM.:fvlxVU:5mAsDwtJsoLm0U2QzcAPbMGoFtYYnOi3Uynm7-iBPXDeXK7FerdNFR',
                tags = [
                    ''
                    ],
                type = '0'
            )
        else:
            return ManagedBackend(
                name = 'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM.:fvlxVU:5mAsDwtJsoLm0U2QzcAPbMGoFtYYnOi3Uynm7-iBPXDeXK7FerdNFR',
                type = '0',
        )
        """

    def testManagedBackend(self):
        """Test ManagedBackend"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
