# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.managed_routing_profile import ManagedRoutingProfile

class TestManagedRoutingProfile(unittest.TestCase):
    """ManagedRoutingProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagedRoutingProfile:
        """Test ManagedRoutingProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagedRoutingProfile`
        """
        model = ManagedRoutingProfile()
        if include_optional:
            return ManagedRoutingProfile(
                fallback = 'none',
                max_cost_usd = 0.0,
                optimize = 'balanced',
                tags = [
                    ''
                    ]
            )
        else:
            return ManagedRoutingProfile(
        )
        """

    def testManagedRoutingProfile(self):
        """Test ManagedRoutingProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
