# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.management_metrics import ManagementMetrics

class TestManagementMetrics(unittest.TestCase):
    """ManagementMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagementMetrics:
        """Test ManagementMetrics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagementMetrics`
        """
        model = ManagementMetrics()
        if include_optional:
            return ManagementMetrics(
                collected_at = '',
                counters = [
                    mmgateway.models.counter_sample.CounterSample(
                        labels = {
                            'key' : ''
                            }, 
                        name = '', 
                        value = 1.337, )
                    ],
                enabled = True,
                histograms = [
                    mmgateway.models.histogram_sample.HistogramSample(
                        count = 56, 
                        labels = {
                            'key' : ''
                            }, 
                        max = 1.337, 
                        mean = 1.337, 
                        min = 1.337, 
                        name = '', 
                        sum = 1.337, )
                    ],
                selection = [
                    mmgateway.models.selection_health.SelectionHealth(
                        account = '', 
                        attempts = 56, 
                        backend = '', 
                        cooldown_remaining_s = 1.337, 
                        latency_s = 1.337, 
                        modality = '', 
                        model = '', 
                        rate_limited = True, 
                        success_rate = 1.337, )
                    ]
            )
        else:
            return ManagementMetrics(
                collected_at = '',
                counters = [
                    mmgateway.models.counter_sample.CounterSample(
                        labels = {
                            'key' : ''
                            }, 
                        name = '', 
                        value = 1.337, )
                    ],
                enabled = True,
                histograms = [
                    mmgateway.models.histogram_sample.HistogramSample(
                        count = 56, 
                        labels = {
                            'key' : ''
                            }, 
                        max = 1.337, 
                        mean = 1.337, 
                        min = 1.337, 
                        name = '', 
                        sum = 1.337, )
                    ],
                selection = [
                    mmgateway.models.selection_health.SelectionHealth(
                        account = '', 
                        attempts = 56, 
                        backend = '', 
                        cooldown_remaining_s = 1.337, 
                        latency_s = 1.337, 
                        modality = '', 
                        model = '', 
                        rate_limited = True, 
                        success_rate = 1.337, )
                    ],
        )
        """

    def testManagementMetrics(self):
        """Test ManagementMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
