# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.input_inner2 import InputInner2

class TestInputInner2(unittest.TestCase):
    """InputInner2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InputInner2:
        """Test InputInner2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InputInner2`
        """
        model = InputInner2()
        if include_optional:
            return InputInner2(
                text = '0',
                type = 'text',
                role = 'reference_video',
                uri = '0'
            )
        else:
            return InputInner2(
                text = '0',
                type = 'text',
                uri = '0',
        )
        """

    def testInputInner2(self):
        """Test InputInner2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
