# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.voice_clone_request import VoiceCloneRequest

class TestVoiceCloneRequest(unittest.TestCase):
    """VoiceCloneRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceCloneRequest:
        """Test VoiceCloneRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceCloneRequest`
        """
        model = VoiceCloneRequest()
        if include_optional:
            return VoiceCloneRequest(
                consent = mmgateway.models.voice_consent.VoiceConsent(
                    granted = true, 
                    language = 'eio', 
                    recording_uri = '0', ),
                input = [
                    mmgateway.models.voice_sample_input.VoiceSampleInput(
                        type = 'audio', 
                        uri = '0', )
                    ],
                metadata = { },
                model = '',
                parameters = mmgateway.models.voice_parameters.VoiceParameters(
                    description = '', 
                    name = 'jUR,rZ#UM/?R,Fp^l6$ARjQJk C>i H\'qT\\{<?\'es#)#iK.YM{Rag2/!KB!k@5oXh.:Ts\";mGL,i&z5[P@M\"lzfB+Y,Twzfu~N^z\"mfqecVU{S0', 
                    remove_background_noise = True, ),
                routing = mmgateway.models.routing_directive.RoutingDirective(
                    budget = null, 
                    fallback = 'none', 
                    max_cost_usd = 0.0, 
                    optimize = 'balanced', 
                    profile = '0', )
            )
        else:
            return VoiceCloneRequest(
                consent = mmgateway.models.voice_consent.VoiceConsent(
                    granted = true, 
                    language = 'eio', 
                    recording_uri = '0', ),
                input = [
                    mmgateway.models.voice_sample_input.VoiceSampleInput(
                        type = 'audio', 
                        uri = '0', )
                    ],
                parameters = mmgateway.models.voice_parameters.VoiceParameters(
                    description = '', 
                    name = 'jUR,rZ#UM/?R,Fp^l6$ARjQJk C>i H\'qT\\{<?\'es#)#iK.YM{Rag2/!KB!k@5oXh.:Ts\";mGL,i&z5[P@M\"lzfB+Y,Twzfu~N^z\"mfqecVU{S0', 
                    remove_background_noise = True, ),
        )
        """

    def testVoiceCloneRequest(self):
        """Test VoiceCloneRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
