# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.voice_consent import VoiceConsent

class TestVoiceConsent(unittest.TestCase):
    """VoiceConsent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceConsent:
        """Test VoiceConsent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceConsent`
        """
        model = VoiceConsent()
        if include_optional:
            return VoiceConsent(
                granted = true,
                language = 'eio',
                recording_uri = '0'
            )
        else:
            return VoiceConsent(
                granted = true,
        )
        """

    def testVoiceConsent(self):
        """Test VoiceConsent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
