# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.api.proxy_api import ProxyApi


class TestProxyApi(unittest.TestCase):
    """ProxyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProxyApi()

    def tearDown(self) -> None:
        pass

    def test_proxy_request_delete(self) -> None:
        """Test case for proxy_request_delete

        Forward a request through a domain-matched proxy
        """
        pass

    def test_proxy_request_get(self) -> None:
        """Test case for proxy_request_get

        Forward a request through a domain-matched proxy
        """
        pass

    def test_proxy_request_head(self) -> None:
        """Test case for proxy_request_head

        Forward a request through a domain-matched proxy
        """
        pass

    def test_proxy_request_options(self) -> None:
        """Test case for proxy_request_options

        Forward a request through a domain-matched proxy
        """
        pass

    def test_proxy_request_patch(self) -> None:
        """Test case for proxy_request_patch

        Forward a request through a domain-matched proxy
        """
        pass

    def test_proxy_request_post(self) -> None:
        """Test case for proxy_request_post

        Forward a request through a domain-matched proxy
        """
        pass

    def test_proxy_request_put(self) -> None:
        """Test case for proxy_request_put

        Forward a request through a domain-matched proxy
        """
        pass


if __name__ == '__main__':
    unittest.main()
