# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.image_parameters import ImageParameters

class TestImageParameters(unittest.TestCase):
    """ImageParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageParameters:
        """Test ImageParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageParameters`
        """
        model = ImageParameters()
        if include_optional:
            return ImageParameters(
                background = '',
                compression = 0.0,
                delivery = 'remote',
                dimensions = mmgateway.models.dimensions.Dimensions(
                    height = 1.0, 
                    width = 1.0, ),
                file_format = '',
                guidance_scale = 0.0,
                inference_steps = 1.0,
                negative_prompt = '',
                output_count = 1.0,
                quality = '',
                seed = 56,
                strength = 0.0,
                style = '',
                watermark = True
            )
        else:
            return ImageParameters(
        )
        """

    def testImageParameters(self):
        """Test ImageParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
