# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.video_input import VideoInput

class TestVideoInput(unittest.TestCase):
    """VideoInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VideoInput:
        """Test VideoInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VideoInput`
        """
        model = VideoInput()
        if include_optional:
            return VideoInput(
                role = 'reference_video',
                type = 'video',
                uri = '0'
            )
        else:
            return VideoInput(
                type = 'video',
                uri = '0',
        )
        """

    def testVideoInput(self):
        """Test VideoInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
