# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.music_task_response import MusicTaskResponse

class TestMusicTaskResponse(unittest.TestCase):
    """MusicTaskResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MusicTaskResponse:
        """Test MusicTaskResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MusicTaskResponse`
        """
        model = MusicTaskResponse()
        if include_optional:
            return MusicTaskResponse(
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                error = { },
                id = '',
                links = { },
                lyrics = '',
                metadata = { },
                model = '',
                object = 'music',
                outputs = [
                    { }
                    ],
                routing = { },
                status = 'pending',
                usage = { }
            )
        else:
            return MusicTaskResponse(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                links = { },
                model = '',
                status = 'pending',
        )
        """

    def testMusicTaskResponse(self):
        """Test MusicTaskResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
