# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmgateway.models.audio_parameters import AudioParameters

class TestAudioParameters(unittest.TestCase):
    """AudioParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AudioParameters:
        """Test AudioParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AudioParameters`
        """
        model = AudioParameters()
        if include_optional:
            return AudioParameters(
                bitrate_kbps = 8.0,
                delivery = 'remote',
                file_format = 'mp3',
                instructions = '0',
                language = 'eio-4aWwWL9-86-DZtaGR-yGFZKk-p4z-a0U0gGb-VjddR-l98FWe-FL9DLWy-Fbsj-7LMde-yl-K0-MG-SM-jsrh-dstl-QUN5-Vd-LPAPqRWM-EqkO-tH-wl-IwkT5yJ-ZfzRn9k-GT',
                sample_rate_hz = 8000.0,
                seed = 0.0,
                speed = 0.25,
                voice = 'default'
            )
        else:
            return AudioParameters(
        )
        """

    def testAudioParameters(self):
        """Test AudioParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
