# coding: utf-8

# flake8: noqa

"""
    mm-gateway

    Unified image, video, and music gateway with separate REST APIs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "ImagesApi",
    "MetaApi",
    "MusicApi",
    "ProxyApi",
    "UsageApi",
    "VideosApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BudgetDirective",
    "BudgetState",
    "Dimensions",
    "EstimateCandidate",
    "EstimateResponse",
    "HealthResponse",
    "ImageInput",
    "ImageOutput",
    "ImageParameters",
    "ImageRequest",
    "ImageTaskResponse",
    "InputInner",
    "InputInner1",
    "InputInner2",
    "LyricsInput",
    "ModelEntry",
    "ModelLimitsEntry",
    "ModelLimitsListResponse",
    "ModelListResponse",
    "ModelSpend",
    "MusicAudioInput",
    "MusicImageInput",
    "MusicOutput",
    "MusicParameters",
    "MusicRequest",
    "MusicTaskResponse",
    "ProblemDetail",
    "ResourceLinks",
    "RoutingDirective",
    "RoutingInfo",
    "TaskError",
    "TextInput",
    "Usage",
    "UsagePeriod",
    "UsageResponse",
    "VideoAudioInput",
    "VideoImageInput",
    "VideoInput",
    "VideoOutput",
    "VideoParameters",
    "VideoRequest",
    "VideoTaskResponse",
]

# import apis into sdk package
from mmgateway.api.images_api import ImagesApi as ImagesApi
from mmgateway.api.meta_api import MetaApi as MetaApi
from mmgateway.api.music_api import MusicApi as MusicApi
from mmgateway.api.proxy_api import ProxyApi as ProxyApi
from mmgateway.api.usage_api import UsageApi as UsageApi
from mmgateway.api.videos_api import VideosApi as VideosApi

# import ApiClient
from mmgateway.api_response import ApiResponse as ApiResponse
from mmgateway.api_client import ApiClient as ApiClient
from mmgateway.configuration import Configuration as Configuration
from mmgateway.exceptions import OpenApiException as OpenApiException
from mmgateway.exceptions import ApiTypeError as ApiTypeError
from mmgateway.exceptions import ApiValueError as ApiValueError
from mmgateway.exceptions import ApiKeyError as ApiKeyError
from mmgateway.exceptions import ApiAttributeError as ApiAttributeError
from mmgateway.exceptions import ApiException as ApiException

# import models into sdk package
from mmgateway.models.budget_directive import BudgetDirective as BudgetDirective
from mmgateway.models.budget_state import BudgetState as BudgetState
from mmgateway.models.dimensions import Dimensions as Dimensions
from mmgateway.models.estimate_candidate import EstimateCandidate as EstimateCandidate
from mmgateway.models.estimate_response import EstimateResponse as EstimateResponse
from mmgateway.models.health_response import HealthResponse as HealthResponse
from mmgateway.models.image_input import ImageInput as ImageInput
from mmgateway.models.image_output import ImageOutput as ImageOutput
from mmgateway.models.image_parameters import ImageParameters as ImageParameters
from mmgateway.models.image_request import ImageRequest as ImageRequest
from mmgateway.models.image_task_response import ImageTaskResponse as ImageTaskResponse
from mmgateway.models.input_inner import InputInner as InputInner
from mmgateway.models.input_inner1 import InputInner1 as InputInner1
from mmgateway.models.input_inner2 import InputInner2 as InputInner2
from mmgateway.models.lyrics_input import LyricsInput as LyricsInput
from mmgateway.models.model_entry import ModelEntry as ModelEntry
from mmgateway.models.model_limits_entry import ModelLimitsEntry as ModelLimitsEntry
from mmgateway.models.model_limits_list_response import ModelLimitsListResponse as ModelLimitsListResponse
from mmgateway.models.model_list_response import ModelListResponse as ModelListResponse
from mmgateway.models.model_spend import ModelSpend as ModelSpend
from mmgateway.models.music_audio_input import MusicAudioInput as MusicAudioInput
from mmgateway.models.music_image_input import MusicImageInput as MusicImageInput
from mmgateway.models.music_output import MusicOutput as MusicOutput
from mmgateway.models.music_parameters import MusicParameters as MusicParameters
from mmgateway.models.music_request import MusicRequest as MusicRequest
from mmgateway.models.music_task_response import MusicTaskResponse as MusicTaskResponse
from mmgateway.models.problem_detail import ProblemDetail as ProblemDetail
from mmgateway.models.resource_links import ResourceLinks as ResourceLinks
from mmgateway.models.routing_directive import RoutingDirective as RoutingDirective
from mmgateway.models.routing_info import RoutingInfo as RoutingInfo
from mmgateway.models.task_error import TaskError as TaskError
from mmgateway.models.text_input import TextInput as TextInput
from mmgateway.models.usage import Usage as Usage
from mmgateway.models.usage_period import UsagePeriod as UsagePeriod
from mmgateway.models.usage_response import UsageResponse as UsageResponse
from mmgateway.models.video_audio_input import VideoAudioInput as VideoAudioInput
from mmgateway.models.video_image_input import VideoImageInput as VideoImageInput
from mmgateway.models.video_input import VideoInput as VideoInput
from mmgateway.models.video_output import VideoOutput as VideoOutput
from mmgateway.models.video_parameters import VideoParameters as VideoParameters
from mmgateway.models.video_request import VideoRequest as VideoRequest
from mmgateway.models.video_task_response import VideoTaskResponse as VideoTaskResponse

