# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BudgetState(BaseModel):
    """
    The state of one budget (a key's period or a client scope).
    """ # noqa: E501
    limit_usd: Optional[Union[StrictFloat, StrictInt]] = None
    remaining_usd: Optional[Union[StrictFloat, StrictInt]] = None
    reserved_usd: Optional[Union[StrictFloat, StrictInt]] = 0.0
    scope: Optional[StrictStr] = None
    spent_usd: Optional[Union[StrictFloat, StrictInt]] = 0.0
    tasks: Optional[StrictInt] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["limit_usd", "remaining_usd", "reserved_usd", "scope", "spent_usd", "tasks"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BudgetState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if limit_usd (nullable) is None
        # and model_fields_set contains the field
        if self.limit_usd is None and "limit_usd" in self.model_fields_set:
            _dict['limit_usd'] = None

        # set to None if remaining_usd (nullable) is None
        # and model_fields_set contains the field
        if self.remaining_usd is None and "remaining_usd" in self.model_fields_set:
            _dict['remaining_usd'] = None

        # set to None if scope (nullable) is None
        # and model_fields_set contains the field
        if self.scope is None and "scope" in self.model_fields_set:
            _dict['scope'] = None

        # set to None if tasks (nullable) is None
        # and model_fields_set contains the field
        if self.tasks is None and "tasks" in self.model_fields_set:
            _dict['tasks'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BudgetState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "limit_usd": obj.get("limit_usd"),
            "remaining_usd": obj.get("remaining_usd"),
            "reserved_usd": obj.get("reserved_usd") if obj.get("reserved_usd") is not None else 0.0,
            "scope": obj.get("scope"),
            "spent_usd": obj.get("spent_usd") if obj.get("spent_usd") is not None else 0.0,
            "tasks": obj.get("tasks")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


