# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from mmgateway.models.budget_state import BudgetState
from mmgateway.models.estimate_candidate import EstimateCandidate
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EstimateResponse(BaseModel):
    """
    The routing and cost a create would get, without creating a task.
    """ # noqa: E501
    budget: Optional[BudgetState] = None
    candidates: Optional[List[EstimateCandidate]] = None
    currency: Optional[StrictStr] = 'USD'
    estimated_cost: Optional[Union[StrictFloat, StrictInt]] = None
    modality: StrictStr
    model: Optional[StrictStr] = None
    object: Optional[StrictStr] = 'estimate'
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["budget", "candidates", "currency", "estimated_cost", "modality", "model", "object"]

    @field_validator('currency')
    def currency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['USD']):
            raise ValueError("must be one of enum values ('USD')")
        return value

    @field_validator('modality')
    def modality_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['image', 'video', 'music', 'audio']):
            raise ValueError("must be one of enum values ('image', 'video', 'music', 'audio')")
        return value

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['estimate']):
            raise ValueError("must be one of enum values ('estimate')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EstimateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of budget
        if self.budget:
            _dict['budget'] = self.budget.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in candidates (list)
        _items = []
        if self.candidates:
            for _item_candidates in self.candidates:
                if _item_candidates:
                    _items.append(_item_candidates.to_dict())
            _dict['candidates'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if budget (nullable) is None
        # and model_fields_set contains the field
        if self.budget is None and "budget" in self.model_fields_set:
            _dict['budget'] = None

        # set to None if estimated_cost (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_cost is None and "estimated_cost" in self.model_fields_set:
            _dict['estimated_cost'] = None

        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EstimateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "budget": BudgetState.from_dict(obj["budget"]) if obj.get("budget") is not None else None,
            "candidates": [EstimateCandidate.from_dict(_item) for _item in obj["candidates"]] if obj.get("candidates") is not None else None,
            "currency": obj.get("currency") if obj.get("currency") is not None else 'USD',
            "estimated_cost": obj.get("estimated_cost"),
            "modality": obj.get("modality"),
            "model": obj.get("model"),
            "object": obj.get("object") if obj.get("object") is not None else 'estimate'
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


