# coding: utf-8

"""
    mm-gateway

    Unified image, video, and music gateway with separate REST APIs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EstimateCandidate(BaseModel):
    """
    EstimateCandidate
    """ # noqa: E501
    admissible: Optional[StrictBool] = True
    estimated_cost: Optional[Union[StrictFloat, StrictInt]] = None
    lifecycle: Optional[StrictStr] = 'active'
    model: StrictStr
    reason: Optional[StrictStr] = Field(default=None, description="Why the candidate is not admissible: limits, retired, max_cost, unpriced or budget.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["admissible", "estimated_cost", "lifecycle", "model", "reason"]

    @field_validator('lifecycle')
    def lifecycle_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'deprecated', 'retired']):
            raise ValueError("must be one of enum values ('active', 'deprecated', 'retired')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EstimateCandidate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if estimated_cost (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_cost is None and "estimated_cost" in self.model_fields_set:
            _dict['estimated_cost'] = None

        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EstimateCandidate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "admissible": obj.get("admissible") if obj.get("admissible") is not None else True,
            "estimated_cost": obj.get("estimated_cost"),
            "lifecycle": obj.get("lifecycle") if obj.get("lifecycle") is not None else 'active',
            "model": obj.get("model"),
            "reason": obj.get("reason")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


