# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManagedTask(BaseModel):
    """
    ManagedTask
    """ # noqa: E501
    backend: StrictStr
    completed_at: Optional[StrictInt] = None
    created_at: StrictInt
    id: StrictStr
    modality: StrictStr
    model: StrictStr
    owner_key_id: StrictStr
    status: StrictStr
    __properties: ClassVar[List[str]] = ["backend", "completed_at", "created_at", "id", "modality", "model", "owner_key_id", "status"]

    @field_validator('modality')
    def modality_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['image', 'video', 'music', 'audio', 'voice']):
            raise ValueError("must be one of enum values ('image', 'video', 'music', 'audio', 'voice')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'running', 'succeeded', 'failed', 'cancelled', 'expired']):
            raise ValueError("must be one of enum values ('pending', 'running', 'succeeded', 'failed', 'cancelled', 'expired')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManagedTask from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManagedTask from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "backend": obj.get("backend"),
            "completed_at": obj.get("completed_at"),
            "created_at": obj.get("created_at"),
            "id": obj.get("id"),
            "modality": obj.get("modality"),
            "model": obj.get("model"),
            "owner_key_id": obj.get("owner_key_id"),
            "status": obj.get("status")
        })
        return _obj


