# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from mmgateway.models.counter_sample import CounterSample
from mmgateway.models.histogram_sample import HistogramSample
from mmgateway.models.selection_health import SelectionHealth
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManagementMetrics(BaseModel):
    """
    ManagementMetrics
    """ # noqa: E501
    collected_at: StrictStr
    counters: List[CounterSample]
    enabled: StrictBool
    histograms: List[HistogramSample]
    selection: List[SelectionHealth]
    __properties: ClassVar[List[str]] = ["collected_at", "counters", "enabled", "histograms", "selection"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManagementMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in counters (list)
        _items = []
        if self.counters:
            for _item_counters in self.counters:
                if _item_counters:
                    _items.append(_item_counters.to_dict())
            _dict['counters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in histograms (list)
        _items = []
        if self.histograms:
            for _item_histograms in self.histograms:
                if _item_histograms:
                    _items.append(_item_histograms.to_dict())
            _dict['histograms'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in selection (list)
        _items = []
        if self.selection:
            for _item_selection in self.selection:
                if _item_selection:
                    _items.append(_item_selection.to_dict())
            _dict['selection'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManagementMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "collected_at": obj.get("collected_at"),
            "counters": [CounterSample.from_dict(_item) for _item in obj["counters"]] if obj.get("counters") is not None else None,
            "enabled": obj.get("enabled"),
            "histograms": [HistogramSample.from_dict(_item) for _item in obj["histograms"]] if obj.get("histograms") is not None else None,
            "selection": [SelectionHealth.from_dict(_item) for _item in obj["selection"]] if obj.get("selection") is not None else None
        })
        return _obj


