# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from mmgateway.models.managed_budget import ManagedBudget
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManagedKey(BaseModel):
    """
    ManagedKey
    """ # noqa: E501
    allow_backends: Optional[List[StrictStr]] = None
    allow_tags: Optional[List[StrictStr]] = None
    budget: Optional[ManagedBudget] = None
    default_audio_backend: Optional[StrictStr] = None
    default_audio_tag: Optional[StrictStr] = None
    default_image_backend: Optional[StrictStr] = None
    default_image_tag: Optional[StrictStr] = None
    default_music_backend: Optional[StrictStr] = None
    default_music_tag: Optional[StrictStr] = None
    default_video_backend: Optional[StrictStr] = None
    default_video_tag: Optional[StrictStr] = None
    deny_tags: Optional[List[StrictStr]] = None
    enabled: Optional[StrictBool] = True
    extra: Optional[Dict[str, Any]] = None
    id: Annotated[str, Field(strict=True)]
    key: StrictStr
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["allow_backends", "allow_tags", "budget", "default_audio_backend", "default_audio_tag", "default_image_backend", "default_image_tag", "default_music_backend", "default_music_tag", "default_video_backend", "default_video_tag", "deny_tags", "enabled", "extra", "id", "key"]

    @field_validator('id', mode="before")
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManagedKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of budget
        if self.budget:
            _dict['budget'] = self.budget.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if budget (nullable) is None
        # and model_fields_set contains the field
        if self.budget is None and "budget" in self.model_fields_set:
            _dict['budget'] = None

        # set to None if default_audio_backend (nullable) is None
        # and model_fields_set contains the field
        if self.default_audio_backend is None and "default_audio_backend" in self.model_fields_set:
            _dict['default_audio_backend'] = None

        # set to None if default_audio_tag (nullable) is None
        # and model_fields_set contains the field
        if self.default_audio_tag is None and "default_audio_tag" in self.model_fields_set:
            _dict['default_audio_tag'] = None

        # set to None if default_image_backend (nullable) is None
        # and model_fields_set contains the field
        if self.default_image_backend is None and "default_image_backend" in self.model_fields_set:
            _dict['default_image_backend'] = None

        # set to None if default_image_tag (nullable) is None
        # and model_fields_set contains the field
        if self.default_image_tag is None and "default_image_tag" in self.model_fields_set:
            _dict['default_image_tag'] = None

        # set to None if default_music_backend (nullable) is None
        # and model_fields_set contains the field
        if self.default_music_backend is None and "default_music_backend" in self.model_fields_set:
            _dict['default_music_backend'] = None

        # set to None if default_music_tag (nullable) is None
        # and model_fields_set contains the field
        if self.default_music_tag is None and "default_music_tag" in self.model_fields_set:
            _dict['default_music_tag'] = None

        # set to None if default_video_backend (nullable) is None
        # and model_fields_set contains the field
        if self.default_video_backend is None and "default_video_backend" in self.model_fields_set:
            _dict['default_video_backend'] = None

        # set to None if default_video_tag (nullable) is None
        # and model_fields_set contains the field
        if self.default_video_tag is None and "default_video_tag" in self.model_fields_set:
            _dict['default_video_tag'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManagedKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allow_backends": obj.get("allow_backends"),
            "allow_tags": obj.get("allow_tags"),
            "budget": ManagedBudget.from_dict(obj["budget"]) if obj.get("budget") is not None else None,
            "default_audio_backend": obj.get("default_audio_backend"),
            "default_audio_tag": obj.get("default_audio_tag"),
            "default_image_backend": obj.get("default_image_backend"),
            "default_image_tag": obj.get("default_image_tag"),
            "default_music_backend": obj.get("default_music_backend"),
            "default_music_tag": obj.get("default_music_tag"),
            "default_video_backend": obj.get("default_video_backend"),
            "default_video_tag": obj.get("default_video_tag"),
            "deny_tags": obj.get("deny_tags"),
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "extra": obj.get("extra"),
            "id": obj.get("id"),
            "key": obj.get("key")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


