# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from mmgateway.models.backend_runtime import BackendRuntime
from mmgateway.models.proxy_runtime import ProxyRuntime
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManagementStatus(BaseModel):
    """
    ManagementStatus
    """ # noqa: E501
    backend_types: List[StrictStr]
    backends: List[BackendRuntime]
    enabled_keys_count: StrictInt
    keys_count: StrictInt
    metrics_enabled: StrictBool
    persistent: StrictBool
    proxies: List[ProxyRuntime]
    revision: StrictStr
    status: Optional[StrictStr] = 'ok'
    tasks_by_status: Dict[str, StrictInt]
    uptime_seconds: Union[StrictFloat, StrictInt]
    version: StrictStr
    __properties: ClassVar[List[str]] = ["backend_types", "backends", "enabled_keys_count", "keys_count", "metrics_enabled", "persistent", "proxies", "revision", "status", "tasks_by_status", "uptime_seconds", "version"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ok']):
            raise ValueError("must be one of enum values ('ok')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManagementStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in backends (list)
        _items = []
        if self.backends:
            for _item_backends in self.backends:
                if _item_backends:
                    _items.append(_item_backends.to_dict())
            _dict['backends'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in proxies (list)
        _items = []
        if self.proxies:
            for _item_proxies in self.proxies:
                if _item_proxies:
                    _items.append(_item_proxies.to_dict())
            _dict['proxies'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManagementStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "backend_types": obj.get("backend_types"),
            "backends": [BackendRuntime.from_dict(_item) for _item in obj["backends"]] if obj.get("backends") is not None else None,
            "enabled_keys_count": obj.get("enabled_keys_count"),
            "keys_count": obj.get("keys_count"),
            "metrics_enabled": obj.get("metrics_enabled"),
            "persistent": obj.get("persistent"),
            "proxies": [ProxyRuntime.from_dict(_item) for _item in obj["proxies"]] if obj.get("proxies") is not None else None,
            "revision": obj.get("revision"),
            "status": obj.get("status") if obj.get("status") is not None else 'ok',
            "tasks_by_status": obj.get("tasks_by_status"),
            "uptime_seconds": obj.get("uptime_seconds"),
            "version": obj.get("version")
        })
        return _obj


