# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from mmgateway.models.proxy_account import ProxyAccount
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManagedProxy(BaseModel):
    """
    ManagedProxy
    """ # noqa: E501
    accounts: Optional[List[ProxyAccount]] = None
    base_url: StrictStr
    domain: Optional[StrictStr] = None
    enabled: Optional[StrictBool] = True
    headers: Optional[Dict[str, StrictStr]] = None
    outbound_proxy: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    timeout: Optional[Union[Annotated[float, Field(strict=True, gt=0.0)], Annotated[int, Field(strict=True, gt=0)]]] = 120
    __properties: ClassVar[List[str]] = ["accounts", "base_url", "domain", "enabled", "headers", "outbound_proxy", "tags", "timeout"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManagedProxy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in accounts (list)
        _items = []
        if self.accounts:
            for _item_accounts in self.accounts:
                if _item_accounts:
                    _items.append(_item_accounts.to_dict())
            _dict['accounts'] = _items
        # set to None if domain (nullable) is None
        # and model_fields_set contains the field
        if self.domain is None and "domain" in self.model_fields_set:
            _dict['domain'] = None

        # set to None if outbound_proxy (nullable) is None
        # and model_fields_set contains the field
        if self.outbound_proxy is None and "outbound_proxy" in self.model_fields_set:
            _dict['outbound_proxy'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManagedProxy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accounts": [ProxyAccount.from_dict(_item) for _item in obj["accounts"]] if obj.get("accounts") is not None else None,
            "base_url": obj.get("base_url"),
            "domain": obj.get("domain"),
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "headers": obj.get("headers"),
            "outbound_proxy": obj.get("outbound_proxy"),
            "tags": obj.get("tags"),
            "timeout": obj.get("timeout") if obj.get("timeout") is not None else 120
        })
        return _obj


