# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from mmgateway.models.music_output import MusicOutput
from mmgateway.models.resource_links import ResourceLinks
from mmgateway.models.routing_info import RoutingInfo
from mmgateway.models.task_error import TaskError
from mmgateway.models.usage import Usage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MusicTaskResponse(BaseModel):
    """
    MusicTaskResponse
    """ # noqa: E501
    completed_at: Optional[datetime] = None
    created_at: datetime
    error: Optional[TaskError] = None
    id: StrictStr
    links: ResourceLinks
    lyrics: Optional[StrictStr] = None
    metadata: Optional[Dict[str, Any]] = None
    model: StrictStr
    object: Optional[StrictStr] = 'music'
    outputs: Optional[List[MusicOutput]] = None
    routing: Optional[RoutingInfo] = None
    status: StrictStr
    usage: Optional[Usage] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["completed_at", "created_at", "error", "id", "links", "lyrics", "metadata", "model", "object", "outputs", "routing", "status", "usage"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['music']):
            raise ValueError("must be one of enum values ('music')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'running', 'succeeded', 'failed', 'cancelled', 'expired']):
            raise ValueError("must be one of enum values ('pending', 'running', 'succeeded', 'failed', 'cancelled', 'expired')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MusicTaskResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in outputs (list)
        _items = []
        if self.outputs:
            for _item_outputs in self.outputs:
                if _item_outputs:
                    _items.append(_item_outputs.to_dict())
            _dict['outputs'] = _items
        # override the default output from pydantic by calling `to_dict()` of routing
        if self.routing:
            _dict['routing'] = self.routing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if lyrics (nullable) is None
        # and model_fields_set contains the field
        if self.lyrics is None and "lyrics" in self.model_fields_set:
            _dict['lyrics'] = None

        # set to None if routing (nullable) is None
        # and model_fields_set contains the field
        if self.routing is None and "routing" in self.model_fields_set:
            _dict['routing'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MusicTaskResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "completed_at": obj.get("completed_at"),
            "created_at": obj.get("created_at"),
            "error": TaskError.from_dict(obj["error"]) if obj.get("error") is not None else None,
            "id": obj.get("id"),
            "links": ResourceLinks.from_dict(obj["links"]) if obj.get("links") is not None else None,
            "lyrics": obj.get("lyrics"),
            "metadata": obj.get("metadata"),
            "model": obj.get("model"),
            "object": obj.get("object") if obj.get("object") is not None else 'music',
            "outputs": [MusicOutput.from_dict(_item) for _item in obj["outputs"]] if obj.get("outputs") is not None else None,
            "routing": RoutingInfo.from_dict(obj["routing"]) if obj.get("routing") is not None else None,
            "status": obj.get("status"),
            "usage": Usage.from_dict(obj["usage"]) if obj.get("usage") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


