# coding: utf-8

"""
    mm-gateway

    Unified image, video, and music gateway with separate REST APIs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MusicParameters(BaseModel):
    """
    MusicParameters
    """ # noqa: E501
    bitrate_kbps: Optional[Annotated[int, Field(strict=True, ge=8)]] = None
    bpm: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    duration_seconds: Optional[Union[Annotated[float, Field(strict=True, gt=0.0)], Annotated[int, Field(strict=True, gt=0)]]] = None
    enhance_lyrics: Optional[StrictBool] = None
    file_format: Optional[StrictStr] = None
    guidance_scale: Optional[Union[Annotated[float, Field(strict=True, ge=0.0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    inference_steps: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    instrumental: Optional[StrictBool] = None
    key: Optional[StrictStr] = None
    negative_prompt: Optional[StrictStr] = None
    novelty: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = None
    output_count: Optional[Annotated[int, Field(le=16, strict=True, ge=1)]] = None
    provenance: Optional[StrictBool] = None
    reference_audio_strength: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = None
    respect_section_durations: Optional[StrictBool] = None
    sample_rate_hz: Optional[Annotated[int, Field(strict=True, ge=8000)]] = None
    scale: Optional[StrictStr] = None
    seed: Optional[StrictInt] = None
    style: Optional[StrictStr] = None
    style_strength: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = None
    time_signature: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    vocal_gender: Optional[StrictStr] = None
    vocal_language: Optional[StrictStr] = None
    voice: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["bitrate_kbps", "bpm", "duration_seconds", "enhance_lyrics", "file_format", "guidance_scale", "inference_steps", "instrumental", "key", "negative_prompt", "novelty", "output_count", "provenance", "reference_audio_strength", "respect_section_durations", "sample_rate_hz", "scale", "seed", "style", "style_strength", "time_signature", "title", "vocal_gender", "vocal_language", "voice"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MusicParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if bitrate_kbps (nullable) is None
        # and model_fields_set contains the field
        if self.bitrate_kbps is None and "bitrate_kbps" in self.model_fields_set:
            _dict['bitrate_kbps'] = None

        # set to None if bpm (nullable) is None
        # and model_fields_set contains the field
        if self.bpm is None and "bpm" in self.model_fields_set:
            _dict['bpm'] = None

        # set to None if duration_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.duration_seconds is None and "duration_seconds" in self.model_fields_set:
            _dict['duration_seconds'] = None

        # set to None if enhance_lyrics (nullable) is None
        # and model_fields_set contains the field
        if self.enhance_lyrics is None and "enhance_lyrics" in self.model_fields_set:
            _dict['enhance_lyrics'] = None

        # set to None if file_format (nullable) is None
        # and model_fields_set contains the field
        if self.file_format is None and "file_format" in self.model_fields_set:
            _dict['file_format'] = None

        # set to None if guidance_scale (nullable) is None
        # and model_fields_set contains the field
        if self.guidance_scale is None and "guidance_scale" in self.model_fields_set:
            _dict['guidance_scale'] = None

        # set to None if inference_steps (nullable) is None
        # and model_fields_set contains the field
        if self.inference_steps is None and "inference_steps" in self.model_fields_set:
            _dict['inference_steps'] = None

        # set to None if instrumental (nullable) is None
        # and model_fields_set contains the field
        if self.instrumental is None and "instrumental" in self.model_fields_set:
            _dict['instrumental'] = None

        # set to None if key (nullable) is None
        # and model_fields_set contains the field
        if self.key is None and "key" in self.model_fields_set:
            _dict['key'] = None

        # set to None if negative_prompt (nullable) is None
        # and model_fields_set contains the field
        if self.negative_prompt is None and "negative_prompt" in self.model_fields_set:
            _dict['negative_prompt'] = None

        # set to None if novelty (nullable) is None
        # and model_fields_set contains the field
        if self.novelty is None and "novelty" in self.model_fields_set:
            _dict['novelty'] = None

        # set to None if output_count (nullable) is None
        # and model_fields_set contains the field
        if self.output_count is None and "output_count" in self.model_fields_set:
            _dict['output_count'] = None

        # set to None if provenance (nullable) is None
        # and model_fields_set contains the field
        if self.provenance is None and "provenance" in self.model_fields_set:
            _dict['provenance'] = None

        # set to None if reference_audio_strength (nullable) is None
        # and model_fields_set contains the field
        if self.reference_audio_strength is None and "reference_audio_strength" in self.model_fields_set:
            _dict['reference_audio_strength'] = None

        # set to None if respect_section_durations (nullable) is None
        # and model_fields_set contains the field
        if self.respect_section_durations is None and "respect_section_durations" in self.model_fields_set:
            _dict['respect_section_durations'] = None

        # set to None if sample_rate_hz (nullable) is None
        # and model_fields_set contains the field
        if self.sample_rate_hz is None and "sample_rate_hz" in self.model_fields_set:
            _dict['sample_rate_hz'] = None

        # set to None if scale (nullable) is None
        # and model_fields_set contains the field
        if self.scale is None and "scale" in self.model_fields_set:
            _dict['scale'] = None

        # set to None if seed (nullable) is None
        # and model_fields_set contains the field
        if self.seed is None and "seed" in self.model_fields_set:
            _dict['seed'] = None

        # set to None if style (nullable) is None
        # and model_fields_set contains the field
        if self.style is None and "style" in self.model_fields_set:
            _dict['style'] = None

        # set to None if style_strength (nullable) is None
        # and model_fields_set contains the field
        if self.style_strength is None and "style_strength" in self.model_fields_set:
            _dict['style_strength'] = None

        # set to None if time_signature (nullable) is None
        # and model_fields_set contains the field
        if self.time_signature is None and "time_signature" in self.model_fields_set:
            _dict['time_signature'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if vocal_gender (nullable) is None
        # and model_fields_set contains the field
        if self.vocal_gender is None and "vocal_gender" in self.model_fields_set:
            _dict['vocal_gender'] = None

        # set to None if vocal_language (nullable) is None
        # and model_fields_set contains the field
        if self.vocal_language is None and "vocal_language" in self.model_fields_set:
            _dict['vocal_language'] = None

        # set to None if voice (nullable) is None
        # and model_fields_set contains the field
        if self.voice is None and "voice" in self.model_fields_set:
            _dict['voice'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MusicParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bitrate_kbps": obj.get("bitrate_kbps"),
            "bpm": obj.get("bpm"),
            "duration_seconds": obj.get("duration_seconds"),
            "enhance_lyrics": obj.get("enhance_lyrics"),
            "file_format": obj.get("file_format"),
            "guidance_scale": obj.get("guidance_scale"),
            "inference_steps": obj.get("inference_steps"),
            "instrumental": obj.get("instrumental"),
            "key": obj.get("key"),
            "negative_prompt": obj.get("negative_prompt"),
            "novelty": obj.get("novelty"),
            "output_count": obj.get("output_count"),
            "provenance": obj.get("provenance"),
            "reference_audio_strength": obj.get("reference_audio_strength"),
            "respect_section_durations": obj.get("respect_section_durations"),
            "sample_rate_hz": obj.get("sample_rate_hz"),
            "scale": obj.get("scale"),
            "seed": obj.get("seed"),
            "style": obj.get("style"),
            "style_strength": obj.get("style_strength"),
            "time_signature": obj.get("time_signature"),
            "title": obj.get("title"),
            "vocal_gender": obj.get("vocal_gender"),
            "vocal_language": obj.get("vocal_language"),
            "voice": obj.get("voice")
        })
        return _obj


