# coding: utf-8

"""
    mm-gateway

    Unified image, video, and music gateway with separate REST APIs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from mmgateway.models.budget_state import BudgetState
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RoutingInfo(BaseModel):
    """
    How auto mode served a task (docs/design/auto-mode.md#fallbacks).
    """ # noqa: E501
    attempts: Optional[StrictInt] = 1
    budget: Optional[BudgetState] = None
    estimated_cost: Optional[Union[StrictFloat, StrictInt]] = None
    fallback: Optional[StrictBool] = False
    fallback_reason: Optional[StrictStr] = None
    optimize: Optional[StrictStr] = 'balanced'
    requested_model: StrictStr
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["attempts", "budget", "estimated_cost", "fallback", "fallback_reason", "optimize", "requested_model"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RoutingInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of budget
        if self.budget:
            _dict['budget'] = self.budget.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if budget (nullable) is None
        # and model_fields_set contains the field
        if self.budget is None and "budget" in self.model_fields_set:
            _dict['budget'] = None

        # set to None if estimated_cost (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_cost is None and "estimated_cost" in self.model_fields_set:
            _dict['estimated_cost'] = None

        # set to None if fallback_reason (nullable) is None
        # and model_fields_set contains the field
        if self.fallback_reason is None and "fallback_reason" in self.model_fields_set:
            _dict['fallback_reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RoutingInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attempts": obj.get("attempts") if obj.get("attempts") is not None else 1,
            "budget": BudgetState.from_dict(obj["budget"]) if obj.get("budget") is not None else None,
            "estimated_cost": obj.get("estimated_cost"),
            "fallback": obj.get("fallback") if obj.get("fallback") is not None else False,
            "fallback_reason": obj.get("fallback_reason"),
            "optimize": obj.get("optimize") if obj.get("optimize") is not None else 'balanced',
            "requested_model": obj.get("requested_model")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


