# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SelectionHealth(BaseModel):
    """
    SelectionHealth
    """ # noqa: E501
    account: StrictStr
    attempts: StrictInt
    backend: StrictStr
    cooldown_remaining_s: Union[StrictFloat, StrictInt]
    latency_s: Optional[Union[StrictFloat, StrictInt]]
    modality: StrictStr
    model: Optional[StrictStr]
    rate_limited: StrictBool
    success_rate: Optional[Union[StrictFloat, StrictInt]]
    __properties: ClassVar[List[str]] = ["account", "attempts", "backend", "cooldown_remaining_s", "latency_s", "modality", "model", "rate_limited", "success_rate"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SelectionHealth from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if latency_s (nullable) is None
        # and model_fields_set contains the field
        if self.latency_s is None and "latency_s" in self.model_fields_set:
            _dict['latency_s'] = None

        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        # set to None if success_rate (nullable) is None
        # and model_fields_set contains the field
        if self.success_rate is None and "success_rate" in self.model_fields_set:
            _dict['success_rate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SelectionHealth from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account": obj.get("account"),
            "attempts": obj.get("attempts"),
            "backend": obj.get("backend"),
            "cooldown_remaining_s": obj.get("cooldown_remaining_s"),
            "latency_s": obj.get("latency_s"),
            "modality": obj.get("modality"),
            "model": obj.get("model"),
            "rate_limited": obj.get("rate_limited"),
            "success_rate": obj.get("success_rate")
        })
        return _obj


