# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from mmgateway.models.input_inner2 import InputInner2
from mmgateway.models.routing_directive import RoutingDirective
from mmgateway.models.video_parameters import VideoParameters
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VideoRequest(BaseModel):
    """
    VideoRequest
    """ # noqa: E501
    input: Annotated[List[InputInner2], Field(min_length=1)] = Field(description="Non-empty ordered video-generation inputs.")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Client-owned metadata returned unchanged with the task.")
    model: Optional[StrictStr] = Field(default=None, description="Model id returned by GET /v1/models, or omit / set to `auto` to let the gateway auto-route to a backend whose limits fit the request's input (modalities, dimensions, duration, ...).")
    parameters: Optional[VideoParameters] = None
    routing: Optional[RoutingDirective] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["input", "metadata", "model", "parameters", "routing"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VideoRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in input (list)
        _items = []
        if self.input:
            for _item_input in self.input:
                if _item_input:
                    _items.append(_item_input.to_dict())
            _dict['input'] = _items
        # override the default output from pydantic by calling `to_dict()` of parameters
        if self.parameters:
            _dict['parameters'] = self.parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of routing
        if self.routing:
            _dict['routing'] = self.routing.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        # set to None if routing (nullable) is None
        # and model_fields_set contains the field
        if self.routing is None and "routing" in self.model_fields_set:
            _dict['routing'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VideoRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "input": [InputInner2.from_dict(_item) for _item in obj["input"]] if obj.get("input") is not None else None,
            "metadata": obj.get("metadata"),
            "model": obj.get("model"),
            "parameters": VideoParameters.from_dict(obj["parameters"]) if obj.get("parameters") is not None else None,
            "routing": RoutingDirective.from_dict(obj["routing"]) if obj.get("routing") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


