# coding: utf-8

"""
    mm-gateway

    Provider-neutral image, video, music, speech and voice cloning gateway.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VoiceConsent(BaseModel):
    """
    VoiceConsent
    """ # noqa: E501
    granted: StrictBool = Field(description="The speaker authorized creation and use of this voice.")
    language: Optional[Annotated[str, Field(strict=True)]] = None
    recording_uri: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Absolute media URI. Inline media uses a base64 data URI.")
    __properties: ClassVar[List[str]] = ["granted", "language", "recording_uri"]

    @field_validator('granted')
    def granted_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['true']):
            raise ValueError("must be one of enum values ('true')")
        return value

    @field_validator('language', mode="before")
    def language_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[a-z]{2,3}$", value):
            raise ValueError(r"must validate the regular expression /^[a-z]{2,3}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VoiceConsent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if recording_uri (nullable) is None
        # and model_fields_set contains the field
        if self.recording_uri is None and "recording_uri" in self.model_fields_set:
            _dict['recording_uri'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VoiceConsent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "granted": obj.get("granted"),
            "language": obj.get("language"),
            "recording_uri": obj.get("recording_uri")
        })
        return _obj


